init project and generate prisma schema
indie-devs/book-exchange-book-service pull request #1
Opened 2022-07-06 12:31 UTC by longbuibao

2022-07-06 12:55 UTC, Balleys1900 submitted a review, later dismissed

2022-07-06 13:44 UTC, duynguyenod commented on package.json
> +    "prisma:migrate": "dotenv -e .env.development -- npx prisma migrate dev",
This should be prisma:generate, then add --name.
Later, when we want to generate migrations, we can call:
yarn prisma:generate "Migration name"

2022-07-06 13:45 UTC, duynguyenod commented on package.json
> +    "prisma:migrate": "dotenv -e .env.development -- npx prisma migrate dev",
You missed the deploy command.
prisma migrate deploy

2022-07-06 13:45 UTC, duynguyenod commented on package.json
> +    "prisma:migrate": "dotenv -e .env.development -- npx prisma migrate dev",
Also, the prisma generate to generate prisma client.

2022-07-06 13:47 UTC, duynguyenod commented on prisma/schema.prisma
> +model Book {
Book should have description, cover image, reprint, number of paper,...
Please, think about a book instead of making a normal object.

2022-07-06 13:48 UTC, duynguyenod commented on prisma/schema.prisma
> +  id    Int    @id @default(autoincrement())
About Author, should we add more info to this object? dob, short bio,...
Please, think about the real life when implementing OOP.

2022-07-06 13:48 UTC, duynguyenod commented on src/app.controller.spec.ts
> +    it('should return "Hello World!"', () => {
Does this test cover any cases in the controller? If not, remove it

2022-07-06 13:49 UTC, duynguyenod commented on src/app.controller.ts
> +export class AppController {
Does this controller helpful? If not, remove it

2022-07-06 13:49 UTC, duynguyenod commented on src/app.service.ts
> +export class AppService {
What is this service for?

2022-07-06 13:49 UTC, duynguyenod commented on src/main.ts
> +  await app.listen(3000);
Put the port to use env var instead of 3000.

2022-07-06 13:50 UTC, duynguyenod commented on test/app.e2e-spec.ts
> +describe('AppController (e2e)', () => {
Does this test cover any cases in the app?

2022-07-06 13:51 UTC, duynguyenod requested changes
Please make sure that classes are necessary.
Also, update the schema for Book.
Better move the Book schema to another branch and PR, this is init project

2022-07-07 06:44 UTC, duynguyenod commented on README.md
> +`npm run prisma:migrate`
Are you sure about this?

2022-07-07 06:44 UTC, duynguyenod requested changes
Check readme

2022-07-07 12:50 UTC, duynguyenod requested changes
Update readme and project to use yarn

2022-07-09 13:20 UTC, duynguyenod approved these changes

2022-07-09 13:22 UTC, Balleys1900 approved these changes

2022-07-09 13:24 UTC, merged